import IMAGE_INDEX from './product-images.json';

/**
 * The product catalogue.
 *
 * **Four families, not eight SKUs.** An earlier pass listed every purchasable
 * line — panels, posts, clamps, spikes, mesh, mesh posts, coils, temporary —
 * as a peer of every other, which put a R 8,06 clamp on the same footing as a
 * whole fencing system and buried what the business actually sells. What it
 * sells is four things: Clear View fencing, razor wire mesh, concertina razor
 * wire, and temporary fencing. Everything else is a component *inside* one of
 * those, and lives in `Product.includes` — which is also the shape the product
 * pages need, since each one opens on its family and then breaks down into
 * exactly these parts.
 *
 * **Photography** comes from `product-images.json`, generated by
 * `scripts/build-product-images.mjs` from the client's "Products 2026" drop.
 * Never hand-edit that JSON — re-run `npm run images`, or the `src`/`srcset`
 * and dimensions drift from the files on disk. Each group is ordered
 * render-first: `images[0]` is the studio engineering render of the assembly,
 * because that is what the range section shows at full size.
 *
 * **Prices** are the client's own published list prices, read off their live
 * storefront (fencing-supplier.com) product by product. ZAR, VAT-inclusive
 * (that storefront prints "R1884,45 Incl. Vat"), and each is a *from* price —
 * the lowest variation of a configurable product, not a flat rate. A family's
 * `priceFrom` is its headline component's from-price: the panel for Clear
 * View, the sheet for razor wire mesh, the coil for concertina.
 *
 * `unit` is only filled where the storefront's own quantity and attribute
 * labels confirm what is being counted ("Clear View Fencing Panels quantity",
 * attributes Aperture / Panel Size / Wire Size / Finishing → per panel).
 * Where it isn't confirmed it stays null and the UI shows a bare "from",
 * rather than inventing a per-metre basis that would be wrong on an invoice.
 * Temporary fencing carries no price at all, because that storefront publishes
 * none for its rapid-deployment range — it renders as "Price on request",
 * which is true, instead of a number that isn't.
 *
 * Metric and ZAR throughout, matching the real business: a Benoni, Gauteng
 * manufacturer quoting in rand.
 */

export interface ProductImage {
  id: string;
  alt: string;
  src: string;
  width: number;
  height: number;
  srcset: string;
}

/** A purchasable component inside a family. */
export interface Component {
  name: string;
  /** Null until that component has a page of its own. */
  href: string | null;
  note: string;
  priceFrom: number | null;
  unit: string | null;
}

export interface Product {
  slug: string;
  /** Where the family links. Families without a page yet route to the estimator. */
  href: string;
  /** True once a dedicated page covers this family. */
  hasPage: boolean;
  name: string;
  /** Short label for rails and cards, where the full name is too long. */
  shortName: string;
  /** One-line positioning, used as the card's kicker. */
  tagline: string;
  blurb: string;
  /** Headline component's from-price, in rand, VAT inclusive. */
  priceFrom: number | null;
  unit: string | null;
  /** Three headline specs — what a buyer scans for. */
  specs: string[];
  /** The parts that make up the family. */
  includes: Component[];
  /**
   * Which technical drawing represents this family in the range section. The
   * four drawings are line art (ui/ProductDrawing.astro), not photographs:
   * four products shot by four people in four conditions never read as one
   * system, and drawing them puts the range in the same language as the rest
   * of the site's cutaways and schematics.
   */
  drawing: 'clear-view' | 'razor-mesh' | 'concertina' | 'temporary';
  /** Text alternative for that drawing — it's content, not decoration. */
  drawingLabel: string;
  /** Client photography, still used by the product pages and galleries. */
  images: ProductImage[];
}

const images = (slug: string): ProductImage[] =>
  (IMAGE_INDEX as Record<string, ProductImage[]>)[slug] ?? [];

/**
 * Rand formatting — comma thousands, period decimal ("R 1,106.00").
 *
 * This is the format the client quotes customers in: their instant-quote
 * estimator prints "Clear view panel 3m W x 1.8m H, plain galv. => R 1,106.00"
 * on every option, and their PDF quote follows it. An earlier version here used
 * the space-and-comma convention ("R 1 884,45") taken from their WooCommerce
 * shop pages — also genuinely theirs, but the wrong one to copy: a price on our
 * page has to match the quote a customer is holding, and they can't be shown
 * the same panel in two notations.
 *
 * `en-US` is the grouping locale, not the currency — the "R" prefix is written
 * explicitly so no locale can substitute a symbol.
 */
export const formatRand = (amount: number): string =>
  `R ${new Intl.NumberFormat('en-US', {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(amount)}`;

/** "From R 550.85 per panel" / "Price on request". */
export const priceLabel = (item: { priceFrom: number | null; unit: string | null }): string => {
  if (item.priceFrom === null) return 'Price on request';
  return `From ${formatRand(item.priceFrom)}${item.unit ? ` ${item.unit}` : ''}`;
};

export const PRODUCTS: Product[] = [
  {
    slug: 'clear-view-fencing',
    href: '/clear-view-fencing-panels',
    hasPage: true,
    name: 'Clear View Fencing',
    shortName: 'Clear View Fencing',
    tagline: '358 anti-climb mesh system',
    blurb:
      'Welded 358 mesh you can see straight through and nobody climbs through — panel, post, clamp and cap engineered together as one system.',
    priceFrom: 550.85,
    unit: 'per panel',
    specs: ['76 × 12.7 mm aperture', '3 m × 1.8–3.0 m panels', 'Galvanised → Plascoat'],
    includes: [
      {
        name: 'Clear View Panels',
        href: '/clear-view-fencing-panels',
        note: '3 apertures · 4 heights · 4 finishes',
        priceFrom: 550.85,
        unit: 'per panel',
      },
      {
        name: 'Clear View Posts',
        href: '/clear-view-fencing-posts',
        note: 'Anti-tamper lip · 3 000 mm centres · solar cap option',
        priceFrom: 217.35,
        unit: 'per post',
      },
      {
        name: 'Spider Clamps & Fixators',
        href: '/fixtures-and-screws',
        note: 'Flat or Spider clamp · tamper-proof screws',
        priceFrom: 8.06,
        unit: 'per clamp',
      },
      {
        name: 'Spikes, Gates & Toppings',
        href: '/accessories',
        note: 'Shark-tooth and wall spikes · gates · solar caps',
        priceFrom: 108.1,
        unit: null,
      },
    ],
    drawing: 'clear-view',
    drawingLabel:
      'Technical drawing of a Clear View system: a capped post carrying a 358 mesh panel under shark-tooth spike topping, with one 76.2 by 12.7 millimetre aperture dimensioned.',
    images: images('clear-view-fencing-panels'),
  },
  {
    slug: 'razor-wire-mesh',
    href: '/quote-estimator',
    hasPage: false,
    name: 'Razor Wire Mesh',
    shortName: 'Razor Wire Mesh',
    tagline: 'Welded blades, not woven wire',
    blurb:
      'Welded razor blade mesh in rolls and rigid sheets — a standalone fence, a wall topping, or a second layer over a line that already exists.',
    priceFrom: 404.8,
    unit: 'per sheet',
    specs: ['Standard & high density', '1.2 m – 2.4 m heights', 'BTO-22 / BTO-30 blades'],
    includes: [
      {
        name: 'Razor Wire Mesh Sheets & Rolls',
        href: null,
        note: 'Standard or high density · 6 m standard lengths',
        priceFrom: 404.8,
        unit: 'per sheet',
      },
      {
        name: 'Main & Stay Posts',
        href: null,
        note: 'Round and square · multiple diameters · painted or HDG',
        priceFrom: 181.72,
        unit: 'per post',
      },
    ],
    drawing: 'razor-mesh',
    drawingLabel:
      'Technical drawing of a welded razor wire mesh sheet, showing the 45 degree diamond lattice with razor blades welded at the nodes.',
    images: images('razor-wire-mesh'),
  },
  {
    slug: 'concertina-razor-wire',
    href: '/quote-estimator',
    hasPage: false,
    name: 'Concertina Razor Wire',
    shortName: 'Concertina Razor Wire',
    tagline: 'Expanding spiral barrier',
    blurb:
      'Coils that expand into a tangled three-dimensional obstacle — single, double or multi-coil, on a fence line, a wall or as a rapid barrier.',
    priceFrom: 362.25,
    unit: 'per coil',
    specs: ['Up to 980 mm diameter', 'Single → multi-coil', 'HDG or PVC coated'],
    includes: [
      {
        name: 'Concertina Coils',
        href: null,
        note: 'Coil diameter and blade profile to spec',
        priceFrom: 362.25,
        unit: 'per coil',
      },
      {
        name: 'Razor Wire Flat Wrap',
        href: null,
        note: 'Flat-profile wrap for walls and existing fence lines',
        priceFrom: 455.4,
        unit: null,
      },
      {
        name: 'Electrified Concertina',
        href: null,
        note: 'Energised coil for detection-grade perimeters',
        priceFrom: 887.8,
        unit: null,
      },
      {
        name: 'Multi-Coil System',
        href: null,
        note: '3D / 6D stacked configurations',
        priceFrom: 1884.45,
        unit: null,
      },
    ],
    drawing: 'concertina',
    drawingLabel:
      'Technical drawing of a concertina razor wire coil expanded between two end brackets, drawn at 980 millimetre diameter with blades on the leading loop.',
    images: images('concertina-razor-wire'),
  },
  {
    slug: 'temporary-fencing',
    href: '/quote-estimator',
    hasPage: false,
    name: 'Temporary Fencing',
    shortName: 'Temporary Fencing',
    tagline: 'A perimeter in an afternoon',
    blurb:
      'Free-standing panels and mobile barrier systems that go up, come down, and go up again somewhere else — for sites, events and interim security.',
    priceFrom: null,
    unit: null,
    specs: ['Free-standing panels', 'Portable & reusable', 'Site, event & interim'],
    includes: [
      {
        name: 'Free-Standing Panels',
        href: null,
        note: 'Braced panels with feet — no groundworks',
        priceFrom: null,
        unit: null,
      },
      {
        name: 'Rapid Deployment Barriers',
        href: null,
        note: 'Cassette and trailer systems, 75 m to 1 000 m+',
        priceFrom: null,
        unit: null,
      },
    ],
    drawing: 'temporary',
    drawingLabel:
      'Technical drawing of two free-standing temporary fence panels on weighted feet, joined by a coupler, requiring no groundworks.',
    images: images('temporary-fencing'),
  },
];

/** Real installation photography — perimeters, not products. */
export const PROJECT_IMAGES: ProductImage[] = images('projects');

/**
 * Pull one specific shot out of a group. Sections that need a particular
 * image (the factory floor, a specific roll stack) reach for this rather than
 * indexing into `images[3]` — an array position silently points at a
 * different photo the moment the manifest is reordered, whereas a missing id
 * returns undefined and the calling template skips the slot.
 */
export const findImage = (slug: string, id: string): ProductImage | undefined =>
  images(slug).find((image) => image.id === id);

export const productBySlug = (slug: string): Product | undefined =>
  PRODUCTS.find((product) => product.slug === slug);
